import Registerform from '@/components/Registerform'
import Head from "next/head";

export default function Home() {
  return (
    <>
     <Head>
        <title>Mmainspire Registration Form</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Registerform/>
      </div>
    
    
    </>
  )
}
